sonar.projectKey=mohamedEMHA_trakl-test
sonar.organization=mohamedemha
sonar.projectName=trakl-test
sonar.projectVersion=1.0.0

sonar.sources=app,components,hooks,lib
sonar.tests=__tests__
sonar.exclusions=**/node_modules/**,**/.expo/**,**/dist/**,**/android/**,**/ios/**,**/lib/locales/**,**/scripts/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/__tests__/**,**/*.d.ts,**/lib/locales/**,**/metro.config.cjs

sonar.typescript.tsconfigPath=tsconfig.json
