import type { LucideIcon } from 'lucide-react-native';
import {
  Activity,
  AlertCircle,
  BarChart2,
  Bell,
  Brain,
  Calendar,
  CalendarDays,
  CheckCircle2,
  CheckSquare,
  Clock,
  Cloud,
  Cpu,
  Droplet,
  Dumbbell,
  Flame,
  Gauge,
  Heart,
  HeartPulse,
  Home as HomeIcon,
  Moon,
  Music,
  Plus,
  Repeat2,
  Scale,
  ShoppingBag,
  SlidersHorizontal,
  Smile,
  Star,
  Sun,
  Target,
  TrendingDown,
  TrendingUp,
  Utensils,
  Wallet,
  Zap,
} from 'lucide-react-native';

/** Named Lucide icons used by the custom tracker builder + dynamic lookups. */
export const ICONS: { key: string; icon: LucideIcon }[] = [
  { key: 'gauge', icon: Gauge },
  { key: 'droplet', icon: Droplet },
  { key: 'flame', icon: Flame },
  { key: 'heart', icon: Heart },
  { key: 'heart-pulse', icon: HeartPulse },
  { key: 'dumbbell', icon: Dumbbell },
  { key: 'activity', icon: Activity },
  { key: 'moon', icon: Moon },
  { key: 'sun', icon: Sun },
  { key: 'star', icon: Star },
  { key: 'zap', icon: Zap },
  { key: 'target', icon: Target },
  { key: 'wallet', icon: Wallet },
  { key: 'utensils', icon: Utensils },
  { key: 'shopping-bag', icon: ShoppingBag },
  { key: 'music', icon: Music },
  { key: 'cloud', icon: Cloud },
  { key: 'cpu', icon: Cpu },
  { key: 'repeat-2', icon: Repeat2 },
  { key: 'check-square', icon: CheckSquare },
];

const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(ICONS.map((i) => [i.key, i.icon]));

export function iconForKey(key: string): LucideIcon {
  return ICON_MAP[key] ?? Gauge;
}

export const FINANCE_CATEGORY_ICON: Record<string, LucideIcon> = {
  Food: Utensils,
  Transport: Activity,
  Home: HomeIcon,
  Health: HeartPulse,
  Entertainment: Music,
  Shopping: ShoppingBag,
  Income: TrendingUp,
};

export {
  Activity,
  AlertCircle,
  BarChart2,
  Bell,
  Brain,
  Calendar,
  CalendarDays,
  CheckCircle2,
  CheckSquare,
  Clock,
  Droplet,
  Flame,
  Moon,
  Plus,
  Repeat2,
  Scale,
  SlidersHorizontal,
  Smile,
  Star,
  TrendingDown,
  TrendingUp,
  Wallet,
  Zap,
};
